# Copyright 2020 Agrista GmbH (https://agrista.com)
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).

{
    "name": "Agri",
    "summary": "Agriculture module to add Farms & Fields",
    "website": "https://github.com/agrista/odoo-agri",
    "category": "Operations/Inventory",
    "version": "0.1.0",
    "sequence": 1,
    "author": "Agrista (Pty) Ltd.",
    "license": "AGPL-3",
    "description": "Agriculture module to add Farms & Fields",
    "depends": ['base', 'base_geoengine', 'mail'],
    "data": [
        'security/agri_security.xml',
        'security/ir.model.access.csv',
        'data/cropping_potential_data.xml',
        'data/effective_depth_data.xml',
        'data/irrigation_type_data.xml',
        'data/land_class_data.xml',
        'data/soil_texture_data.xml',
        'data/terrain_data.xml',
        'data/water_source_data.xml',
        'data/water_source_data.xml',
        'data/res_partner_data.xml',
        'views/agri_menus.xml',
        'views/agri_farm_views.xml',
        'views/res_config_settings_views.xml',
        'views/res_partner_views.xml',
    ],
    "demo": [],
    "application": True,
    "installable": True,
    "auto_install": False,
}
